version: 2.1

jobs:
  bar:
    docker:
      image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo "building"
      - run:
          command: echo "testing"
      - run:
          command: echo "eating"
          
workflows:
  build:
    jobs:
      - bar:
          pre-steps: # steps to run before steps defined in the job bar
            - run:
                command: echo "install custom dependency"
          post-steps: # steps to run after steps defined in the job bar
            - run:
                command: echo "upload artifact to s3"