version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

parameters:
  env:
    type: string
    default: dev

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.3.1

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - continuation/continue:
          configuration_path: .circleci/<< pipeline.parameters.env >>-config.yml # use newly generated config to continue
          parameters: |
            {"env":"<< pipeline.parameters.env >>"}

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup