version: 2.1

parameters:
  env:
    type: string
    default: ""
  param:
    type: string
    default: ""

jobs:
  prd:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo "<< pipeline.parameters.env >> building << pipeline.parameters.param >>"
          
workflows:
  build:
    jobs:
      - prd:
          filters:
            tags:
              only: /.*/
          type: approval