version: 2.1

parameters:
  env:
    type: string
    default: ""
  param:
    type: string
    default: ""

jobs:
  prd:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
            git clone https://bigin_service:$BITBUCKET_TOKEN@bitbucket.org/applicatTeam/bigin-helm-chart.git
            ls -l      
      - run:
          command: echo "<< pipeline.parameters.env >> building << pipeline.parameters.param >>"

  build:
    docker:
      - image: cimg/base:stable
    steps:    
      - run:
          command: echo "<< pipeline.parameters.env >> building << pipeline.parameters.param >>"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:    
      - run:
          command: echo "<< pipeline.parameters.env >> building << pipeline.parameters.param >>"

          
workflows:
  build:
    jobs:
      - prd:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - prd
      - deploy:
          filters:
            tags:
              only: /.*/
          requires:
            - build
