name: Trigger Build

on:
  push:
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+-dev[0-9]+'

jobs:
  trigger_build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CircleCI
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          curl -u ${CIRCLE_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
            "tag":"'"${GITHUB_REF##*/}"'",
            "parameters": {
              "env":"prd"
            }
          }' https://circleci.com/api/v2/project/gh/${GITHUB_REPOSITORY}/pipeline





# curl -X POST \
# -H "Circle-Token: ${CIRCLE_TOKEN}" \
# -H 'Content-Type: application/json' \
# -H 'Accept: application/json' \
# -d '{"branch":"main","parameters":{"env":"prd","trigger":true}}' \
# https://circleci.com/api/v2/project/gh/${GITHUB_REPOSITORY}/pipeline